### PR TITLE
fix(summary): exclude `container_id` from `system_summary` table

### LINKED ISSUE #668: [bug] multiple entries for same process in karmor summary (vault app)
Screenshot:
image

To Reproduce this issue:
```console
$ helm repo add hashicorp https://helm.releases.hashicorp.com
"hashicorp" has been added to your repositories

$ helm install vault hashicorp/vault
```
and run `karmor summary`

### PR DESCRIPTION
**Pull request by yasin-cs-ko-ak**
## Issue:
Repeated entries in `system_summary `table due to different `container_id` when pod restarts.

## Description:
Every time a pod restarts, it creates a new `container_id.` This results in repeated entries in the `system_summary` table for the same pod and container, causing issues with data analysis when we are using karmor summary in CLI.

## Fix:
To prevent repeated entries in the `system_summary` table, this PR exclude the `container_id` field from the `upsertSysSummarySQL` function. Instead, the function will now use the `podname` field to check for existing entries and update them accordingly. This will ensure that only one entry exists in the table for each unique pod, regardless of how many times the container is restarted.

### CODE REVIEW

**Review by seswarrajan — CHANGES_REQUESTED** [review]
Also remove ContainerID from types/observability.go Line: 105

**Comment by yasin-cs-ko-ak** [comment]
> Also remove ContainerID from types/observability.go Line: 105

if we remove the type from there, container_id will be completely removed from the db after that we can't test anything. we are only excluding the container_id.

File: src/libs/dbHandler.go [hunk 1]
```diff
@@ -425,8 +427,13 @@ func UpsertSystemSummary(cfg types.ConfigDB, summaryMap map[types.SystemSummary]
 }
 
 func upsertSysSummarySQL(db *sql.DB, summary types.SystemSummary, timeCount types.SysSummaryTimeCount) error {
+	// sorts pod labels upon pod restart
+	sortLabels := summary.Labels
+	sortedLabels := strings.Split(sortLabels, ",")
+	sort.Strings(sortedLabels)
```
Comment (vishnusomank) [inline src/libs/dbHandler.go:432]: @yasin-cs-ko-ak  What is this code doing?

**Comment by yasin-cs-ko-ak** [comment]
Before sorting the labels

before-labels

After sorting the labels

after-labels

cc: @vishnusomank

**Comment by yasin-cs-ko-ak** [comment]
**Before this fix:**

before-fix

**After this fix:** (there is no repeated entries)

after-fix

cc: @vishnusomank

**Review by vishnusomank — APPROVED** [review]

**Review by nyrahul — APPROVED** [review]

**Review by seswarrajan — APPROVED** [review]
LGTM

**Comment by seswarrajan** [comment]
The reason for removing container_id from system_summary table is that to avoid repetitive logs. Do we not need the same for observability as well. We can remove container_id in summary from being sent to DEO.

@nyrahul @yasin-cs-ko-ak @vishnusomank @wazir-ahmed @AmanKumar2696  WDYT ?

**Comment by nyrahul** [comment]
What is the purpose of observability table vs system summary table? @seswarrajan

**Comment by seswarrajan** [comment]
> What is the purpose of observability table vs system summary table? @seswarrajan

We do not have separate observability table @nyrahul 
What i meant to mention is that can we disable ContainerID field from being sent to DEO ?

**Comment by AmanKumar2696** [comment]
> The reason for removing container_id from system_summary table is that to avoid repetitive logs. Do we not need the same for observability as well. We can remove container_id in summary from being sent to DEO.
> 
> @nyrahul @yasin-cs-ko-ak @vishnusomank @wazir-ahmed @AmanKumar2696 WDYT ?

In App Behaviour, we're not using ```container_id``` for any searching/filtering. Removing it should not affect any existing APIs.

**Comment by yasin-cs-ko-ak** [comment]
We are only removing `container_id` from update query. So we can resolve this issue with minimal code changes.
