### PR TITLE
fix(K8sNetworkPolicy):Fix for network policy not getting generated

### LINKED ISSUE #759: Network Policy is not getting for latest DE image
The k8s nw policies are not getting generated when using the latest DE image.

### PR DESCRIPTION
**Pull request by seswarrajan**
**Purpose of PR?**: Network policies for kubearmor is not getting generated
With the current code, we are failing to update the NetworkLogMap when the network policy log source is Kubearmor. 
Fixed that issue now with this PR

Fixes #

**Does this PR introduce a breaking change?** No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Network policy generation using wordpress-mysql deployment.

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #[https://github.com/accuknox/discovery-engine/issues/759]
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by wazir-ahmed** [comment]
@seswarrajan Can you update PR description on why the previous code was not working? I see that even with this PR, we're using pretty much the same logic?

**Comment by seswarrajan** [comment]
@wazir-ahmed Updated the PR description. Please check.

File: src/plugin/kubearmor.go [hunk 1]
```diff
@@ -581,101 +581,92 @@ func GetNetworkLogsFromKubeArmor() []*pb.Alert {
...
-			}
-			destPod, destLabels, destNs := cluster.ExtractPodSvcInfoFromIP(ip, kalog.ClusterName, pods, services)
+	// Direction
+	if strings.Contains(kaNwLog.Data, "tcp_") {
+		knoxNetLog.Protocol = libs.IPProtocolTCP
+		if strings.Contains(kaNwLog.Data, "tcp_accept") {
+			knoxNetLog.Direction = "INGRESS"
+		} else if strings.Contains(kaNwLog.Data, "tcp_connect") {
+			knoxNetLog.Direction = "EGRESS"
+		}
```
Comment (nyrahul) [inline src/plugin/kubearmor.go:610]: Please handle the unknown `else {}` scnenario too

**Review by nyrahul — DISMISSED** [review]

**Comment by nyrahul** [comment]
The function `getAggregatedSummaryMap` is a good candidate to have unit tests for.

**Comment by seswarrajan** [comment]
@nyrahul This will be handled as part of summary aggregation PR

File: src/plugin/kubearmor.go [hunk 2]
```diff
@@ -581,101 +585,94 @@ func GetNetworkLogsFromKubeArmor() []*pb.Alert {
...
+		knoxNetLog.DstIP = ip
+		knoxNetLog.DstPort, _ = strconv.Atoi(port)
+		knoxNetLog.SynFlag = true
+	} else if strings.Contains(kaNwLog.Data, "SYS_BIND") {
+		var port string
+		// TODO : Identify a way to get protocol from kubearmor
+		// knoxNetLog.Protocol = libs.IPProtocolUDP
+
+		resSlice := strings.Split(kaNwLog.Resource, " ")
```
Comment (achrefbensaad) [inline src/plugin/kubearmor.go]: can you please change the variable name, to something else. it can be easily confused with variable `resslice` in line614

**Review by achrefbensaad — APPROVED** [review]
LGTM, Only once comment regarding var naming.

**Review by achrefbensaad — APPROVED** [review]
LGTM

File: src/plugin/kubearmor.go [hunk 3]
```diff
@@ -404,7 +404,9 @@ func StartKubeArmorRelay(StopChan chan struct{}, cfg types.ConfigKubeArmorRelay)
 		defer func() {
 			log.Info().Msg("watchlogs returning")
 			KubeArmorRelayStarted = false
-			_ = conn.Close()
+			if conn != nil {
+				_ = conn.Close()
+			}
```
Comment (Ankurk99) [inline src/plugin/kubearmor.go]: instead of checking the nil pointer here, it would be better if we can have it while calling the function:
```
	conn := ConnectKubeArmorRelay(cfg)
	if conn == nil {
		// handle error
	}
```

File: src/plugin/kubearmor.go [hunk 4]
```diff
@@ -493,7 +495,9 @@ func StartKubeArmorRelay(StopChan chan struct{}, cfg types.ConfigKubeArmorRelay)
 		defer func() {
 			log.Info().Msg("watchalerts returning")
 			KubeArmorRelayStarted = false
-			_ = conn.Close()
+			if conn != nil {
+				_ = conn.Close()
+			}
```
Comment (Ankurk99) [inline src/plugin/kubearmor.go]: this won't be required if above change is done

**Review by Ankurk99 — CHANGES_REQUESTED** [review]
changes verified locally, mostly LGTM... just some nits

**Review by Ankurk99 — APPROVED** [review]
LGTM
