### PR TITLE
fix logic for missing kubearmor-relay deployment

### LINKED ISSUE #703: index out of range
```
❯ k logs -n accuknox-agents   discovery-engine-5469f46499-cbtbv --previous
1:47PM INF usr/src/knox/src/libs/common.go:76 > BUILD-INFO: commit:ce80984, branch: dev, date: 2023-03-29T03:25:50Z, version: 0.1
1:47PM INF usr/src/knox/src/main.go:33 > NETWORK-POLICY: {OperationMode:1 OperationTrigger:5 CronJobTimeInterval:@every 0h0m10s OneTimeJobTimeSelection: NetworkLogLimit:10000 NetworkLogFrom:kubearmor NetworkLogFile: NetworkPolicyTo:db NetworkPolicyDir:./ NsFilter:[] NsNotFilter:[kube-system] NetPolicyTypes:3 NetPolicyRuleTypes:1023 NetPolicyCIDRBits:32 NetLogFilters:[] NetPolicyL3Level:1 NetPolicyL4Level:1 NetPolicyL7Level:1 NetSkipCertVerification:true}
1:47PM INF usr/src/knox/src/main.go:34 > CILIUM: {HubbleURL:hubble-relay.kube-system.svc.cluster.local HubblePort:80}
1:47PM INF usr/src/knox/src/main.go:35 > SYSTEM-POLICY: {OperationMode:1 OperationTrigger:5 CronJobTimeInterval:@every 0h0m10s OneTimeJobTimeSelection: SystemLogLimit:10000 SystemLogFrom:kubearmor SystemLogFile: SystemPolicyTo:db SystemPolicyDir:./ SysPolicyTypes:7 DeprecateOldMode:true SystemLogFilters:[] NsFilter:[] NsNotFilter:[kube-system] FromSourceFilter:[knoxAutoPolicy] ProcessFromSource:true FileFromSource:true}
1:47PM INF usr/src/knox/src/main.go:36 > KUBEARMOR: {KubeArmorRelayURL:kubearmor.kube-system.svc.cluster.local KubeArmorRelayPort:32767}
1:47PM INF usr/src/knox/src/networkpolicy/networkPolicy.go:2362 > Auto network policy discovery cron job started
1:47PM INF usr/src/knox/src/systempolicy/systemPolicy.go:1492 > Auto system policy discovery cron job started
1:47PM INF usr/src/knox/src/observability/observability.go:79 > Observability cron job started
1:47PM INF usr/src/knox/src/observability/observability.go:97 > Publisher cron job started
1:47PM INF usr/src/knox/src/recommendpolicy/recommendPolicy.go:73 > Recommended policy cron job started
panic: runtime error: index out of range [0] with length 0

goroutine 38 [running]:
github.com/accuknox/auto-policy-discovery/src/cluster.GetKubearmorRelayURL()
        /usr/src/knox/src/cluster/k8sClientHandler.go:497 +0x185
github.com/accuknox/auto-policy-discovery/src/systempolicy.StartSystemLogRcvr()
        /usr/src/knox/src/systempolicy/systemPolicy.go:1466 +0x53
created by github.com/accuknox/auto-policy-discovery/src/systempolicy.StartSystemCronJob
        /usr/src/knox/src/systempolicy/systemPolicy.go:1481 +0x25
```

### PR DESCRIPTION
**Pull request by Ankurk99**
fix: #703

### CODE REVIEW

File: src/systempolicy/systemPolicy.go [hunk 1]
```diff
@@ -1464,6 +1464,9 @@ func StartSystemLogRcvr() {
 	for {
 		if cfg.GetCfgSystemLogFrom() == "kubearmor" {
 			url := cluster.GetKubearmorRelayURL()
+			if url == "" {
+				log.Error().Msg("kubearmor-relay url not found, retrying...")
```
Comment (nyrahul) [inline src/systempolicy/systemPolicy.go:1468]: Shouldn't we return here?

**Review by nyrahul — CHANGES_REQUESTED** [review]

**Review by nyrahul — APPROVED** [review]

**Review by daemon1024 — APPROVED** [review]

File: src/systempolicy/systemPolicy.go [hunk 2]
```diff
@@ -1464,6 +1464,17 @@ func StartSystemLogRcvr() {
...
+				for i := 0; i < 6; i++ {
```
Comment (seswarrajan) [inline src/systempolicy/systemPolicy.go]: Why is there a hardcoded value of  6?

Comment (Ankurk99) [reply src/systempolicy/systemPolicy.go]: it's trying connecting to kubeamor-relay, 6 is the max number of tries. We have 10 sec sleep, so trying 6 times gives us a minute of sleep before we return.

Comment (seswarrajan) [reply src/systempolicy/systemPolicy.go]: @Ankurk99 Can you set a constant for this in types/constants.go and read/use it from there.

Comment (seswarrajan) [reply src/systempolicy/systemPolicy.go]: Or.. Is it OK to read the retry timeout and no.of.times as a configuration from config file and use it here ?
@nyrahul WDYT ?

**Review by seswarrajan — APPROVED** [review]
LGTM

File: src/systempolicy/systemPolicy.go [hunk 3]
```diff
@@ -1464,6 +1464,17 @@ func StartSystemLogRcvr() {
...
+			if url == "" {
+				log.Error().Msg("kubearmor-relay url not found, retrying...")
+				for i := 0; i < types.Maxtries; i++ {
+					time.Sleep(10 * time.Second)
+					url = cluster.GetKubearmorRelayURL()
+					if url != "" {
+						break
+					}
+				}
+				return
```
Comment (Shreyas220) [inline src/systempolicy/systemPolicy.go:1476]: are we sure we want to return here 
doing this would mean if we install kubearmor after the 6 retries the discovery engine wont be able to connect to the relay server

Comment (Ankurk99) [reply src/systempolicy/systemPolicy.go:1476]: Yes, the aim here is to try to look for kubearmor-relay for 60 seconds and the pod will terminate and restart if it couldn't find the relay server.
I think it should be fine to return.

**Review by Shreyas220 — APPROVED** [review]
LGTM :+1:
